### ISSUE TITLE
Contributing visible anchor

### ISSUE THREAD

**Issue by matthiasclasen** [projectatomic/atomic-site-new#9]
There's an anchor in the Contributing heading, which shows up as an unexpected green box. Adding a class="nosymbol" gets rid of the box, but the underline is still there. That could probably be fixed with some more css, but is the anchor actually used as a target anywhere ? Grepping for it comes up empty, so maybe it can just be removed ?

**Comment by matthiasclasen** [comment]
The Documentation heading has the same issue.

**Comment by sanjabonic** [comment]
That's because it's just old content migrated with some minor fixes. Please no content issues opened until we've officially announced the new website beta - there are way too many for now and I'm fixing them one by one.

Feel free to fix and edit content and send PRs if you have the bandwidth, though. :)
